server:
  port: 3010

spring:
  application:
    name: gateway
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        enabled: true
    gateway:
      routes:
        - id: stock
          uri: lb://stock
          predicates:
            - Path=/stock/**
          filters:
            - StripPrefix=1
            - name: RequestRateLimiter
              args:
                key-resolver: '#{@myKeyResolver}'
                redis-rate-limiter.replenishRate: 10
                redis-rate-limiter.burstCapacity: 20
        - id: order
          uri: lb://order
          predicates:
            - Path=/order/**
          filters:
            # 此处应加StripPrefix参数，代表在转发时，忽略路径中的n段参数，否则会报404
            - StripPrefix=1
            - name: RequestRateLimiter
              args:
                key-resolver: '#{@myKeyResolver}'
                redis-rate-limiter.replenishRate: 10
                redis-rate-limiter.burstCapacity: 20
      # 开启网关转发，该设置生成后，之前配置的所有过滤器都将失效，当有个性化网关转发时，必须要禁用该设置
  #      discovery:
  #        locator:
  #          enabled: true
  redis:
    host: 192.168.198.130
    port: 6379
    password:
    timeout: 1000
    jedis:
      pool:
        max-idle: 200
        max-wait: 1
        min-idle: 0