server:
  port: 3010

spring:
  application:
    name: gateway
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        enabled: true
    gateway:
      routes:
        - id: stock
          uri: lb://stock
          predicates:
            - Path=/stock/**
        - id: order
          uri: lb://order
          predicates:
            - Path=/order/**
      # 开启网关转发，不设置该属性会转发失败，报404
      discovery:
        locator:
          enabled: true
