server:
  port: 3010

spring:
  application:
    name: gateway
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        enabled: true
    gateway:
      routes:
        - id: stock
          uri: lb://stock
          predicates:
            - Path=/stock/**
        - id: order
          uri: lb://order
          predicates:
            - Path=/order/**
      #          filters:
      #            - StripPrefix=1
      #            # 限流过滤器，使用gateway内置令牌算法
      #            - name: RequestRateLimiter
      #              args:
      #                # 令牌桶每秒填充平均速率,即行等价于允许用户每秒处理多少个请求平均数
      #                redis-rate-limiter.replenishRate: 10
      #                # 令牌桶的容量，允许在一秒钟内完成的最大请求数
      #                redis-rate-limiter.burstCapacity: 20
      #                # 用于限流的键的解析器的 Bean 对象的名字。它使用 SpEL 表达式根据#{@beanName}从 Spring 容器中获取 Bean 对象。
      #                key-resolver: "#{@rateLimiter}"
      # 开启网关转发，不设置该属性会转发失败，报404
      discovery:
        locator:
          enabled: true
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    timeout: 1000
    jedis:
      pool:
        max-idle: 200
        max-wait: 1
        min-idle: 0